project:
  type: website

website:
  title: "FOI-reports"
  description: "Sequence reports"
  navbar:
    title: "FOI-reports"
    left:
      - text: Main
        href: index.qmd
      - text: Metagenomics
        href: reports/metagenomics.qmd
      - text: Genomic bacteria
        href: reports/bacteria.qmd
      - text: Genomic virus
        href: reports/bacteria.qmd
      - text: About
        href: about.qmd
  page-footer:
    left: 2025 Caroline Öhrman
    right: Made with [Quarto](https://quarto.org)


format:
  html:
    theme:
      - cosmo
      - custom.scss
    css: styles.css
    toc: true



